#services:
#  postgres:
#    image: 'postgres:15'
#    environment:
#      - 'POSTGRES_PASSWORD=postgres'
#      - 'POSTGRES_USER=postgres'
#      - 'POSTGRES_DB=postgres'
#    ports:
#      - '9876:5432'
#    restart: unless-stopped
#
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - postgres
#    restart: unless-stopped
services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '9876:5432'